# Generated by Django 3.1.7 on 2021-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210626_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='new',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='new',
            name='quote',
            field=models.CharField(max_length=200, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text_1',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text_2',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
