# Generated by Django 3.1.7 on 2021-06-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20210626_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='chech',
            new_name='check',
        ),
        migrations.AddField(
            model_name='comment',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
