# Generated by Django 3.1.7 on 2021-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20210626_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='check',
            field=models.BooleanField(),
        ),
    ]
