# Generated by Django 3.1.7 on 2021-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20210626_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='check',
        ),
    ]
