# Generated by Django 3.1.7 on 2021-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_remove_review_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='check',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
